### ISSUE TITLE
Expect(mockFoo.Foo)To(BeCalled(With("foo", 5), Returning("bar, nil))

### ISSUE THREAD

**Issue by poy** [apoydence/eachers#1]
This is another style of matcher that would be very valuable. Ideally, it could integrate with the `Each` matcher as well.

I don't know about the `Returning()` bit, but I think it warrants discussion.

**Comment by poy** [comment]
Does pull #2 resolve this? Or do you think we still need the `Returning()` part?

**Comment by nelsam** [comment]
I thought on it and decided it seemed silly.  Too few use cases to provide specialized functionality for it, really.  Plus, the functionality might be misleading - it might encourage people to use it outside of multi-threaded contexts, which obviously won't work.

I really do wish I could extract the receiver from the method, but I haven't figured it out so far.  I was going so far as to read the reflection package's code to see if I could do some magic with `unsafe.Pointer`s ... so far as I can tell, no dice.
